---
- name: Create ssh folder
  shell: mkdir -p ~/.ssh/

- name: Copy Key file to server
  copy: src=/tmp/fetched/id_rsa.pub dest=~/.ssh/authorized_keys

- name: Chmod SSH Key
  shell: chmod -R 700 ~/.ssh/

- name: Create Folder
  command: mkdir -p /var/www/vhosts/{{ server_hostname }}/

- name: Add user "web_user"
  user: name={{ web_user }} group=apache home=/var/www/vhosts/{{ server_hostname }}

- name: Change ownership of magento to user created and group apache
  file: path=/var/www/vhosts/{{ server_hostname }}/ owner={{ web_user }} group=apache state=directory recurse=yes